name: Reusable deployment workflow

on:
    workflow_call:
        inputs:
            target-env:
                required: true
                type: string

jobs:
    deploy:
        name: Deploy to ${{ inputs.target-env }}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        outputs:
            latest_commit: ${{ steps.git_remote.outputs.latest_commit }}
        environment:
            name: ${{ inputs.target-env }}
        steps:
            - run: echo "🎉 target environment ${{ inputs.target-env }}"
            # - run: echo "🎉 target environment inputs.target-env"
            - run: echo "🍏 is test  ${{ inputs.target-env }} == 'test'"
            - run: echo "🐧 is prod  ${{ inputs.target-env }} == 'prod'"

            # - name: Download artifact from build job
            #   uses: actions/download-artifact@v3
            #   with:
            #     name: cdk-ssm-deployer

            # - name: unzip artifact for deployment
            #   run: unzip release.zip

            # - name: Git clone the repository
            #   uses: actions/checkout@v1
            # Download and unzip the release

            - name: Get Github release
              id: get-release
              run: |
                  RELEASE_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest"
                  RELEASE_JSON=`curl --header 'authorisation: token ${{ github.token }}' -s $RELEASE_URL`
                  VERSION=`echo $RELEASE_JSON | jq '.tag_name' | tr -d '"' | sed -e "s/^v//"`
                  echo "::set-output name=VERSION::$VERSION"
                  echo "Version $VERSION"
                  TARBALL_URL=`echo $RELEASE_JSON | jq '.tarball_url' | tr -d '"'`
                  echo "::set-output name=TARBALL_URL::$TARBALL_URL"
                  echo "Tarball URL: $TARBALL_URL"
            - name: Download tarball
              id: download-tarball
              env:
                  VERSION: ${{ steps.get-release.outputs.VERSION }}
                  TARBALL_URL: ${{ steps.get-release.outputs.TARBALL_URL }}
              run: |
                  OUTPUT_FILE="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}.VERSION.tar.gz"
                  echo "Output file: $OUTPUT_FILE"
                  echo "::set-output name=OUTPUT_FILE::$OUTPUT_FILE"
                  curl --header 'authorisation: token ${{ github.token }}' -L $TARBALL_URL -o $OUTPUT_FILE
            - name: Extract tarball and enter dir
              run: |
                  tar -xfz ${{ steps.download-tarball.outputs.OUTPUT_FILE }}
                  ls -l

            # - name: Assume role using OIDC
            #   uses: aws-actions/configure-aws-credentials@master
            #   with:
            #       role-to-assume: arn:aws:iam::075487384540:role/SSMDeployer-OIDCStack-DeployRole885297C3-F1O3UKF3OLJY
            #       aws-region: ap-southeast-2

            # - uses: actions/setup-node@v2
            #   with:
            #       node-version: '18'

            # - run: yarn install

            # - run: yarn "cdk-deploy-${{ inputs.target-env }}"
